[package]
name = "tree_sitter_parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "tree_sitter_parser"
path = "src/lib.rs"

[dependencies]
tree-sitter = "0.20"
tree-sitter-typescript = "0.20"
anyhow = "1.0"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }